on: push
jobs:
   test-action:
      runs-on: ubuntu:latest
      steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: greetings
        with:
           who-to-greet: FRED
      - run: |
            echo "Action executed at ${{ steps.greetings.outputs.time }}"
